services:
  - type: web
    name: planprod
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python serveur.py
    envVars:
      - key: PORT
        value: 10000

databases:
  - name: planprod-db
    plan: free
    databaseName: planprod
